HOST: 127.0.0.1
PORT: 8080
DEBUG: false

DEV_MODE: true
SHOW_API_DOC: true

API_V1_STR: "/api"
PROJECT_NAME: "tip-ws-report"
AUD_JWT_NAME_FOR_VALIDATION: "tip-ws-report"

TOKEN_EXP_TIME: 3600

DATABASE_URL: 'mongodb://localhost:27017/threat_report'
DATABASE_ACCOUNT: 'mongodb://localhost:27017/ti_account'
URL_MAIL: 'http://mail.vti.com/send'

FOLDER_STORE_FILE: "file_store"

LOGGING_LEVEL: 3
WORKERS: 1

GATEKEEPER_PUBLIC_KEY: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnHfEaHEUBn37uOWP3zVq
  5PBoYrZ4KDUi76Q/Qz5jtghmDoZHo9VctseMn7wy/2F4+7zZ6mBAiAnbLAFDjY6m
  coc4NJ2RfTmBP2ve+sMFLrVlbfvo00szqeF/TCpSAku+94FUpGPvXdIBFsarYTsk
  pq9pbZbz1Ts3D8OFQyvOaCpPUx3WsBb5uoVFmYVYm+gTsLOQqjcgmoi0KoWVI3tM
  175WrFlN/DA/F6ytSuYJqIYBbG0PzI0SqrEVjDhwn1jGs5lr2EUstjH3yPOa8kGN
  WnTkt/m8rvZjS/bKKBZadyWx0Mxi5jjkzsvpyjujr0FPtojsJHGDW1xGDFmXsU0p
  dwIDAQAB
  -----END PUBLIC KEY-----
GATEKEEPER_PRIVATE_KEY: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEAnHfEaHEUBn37uOWP3zVq5PBoYrZ4KDUi76Q/Qz5jtghmDoZH
  o9VctseMn7wy/2F4+7zZ6mBAiAnbLAFDjY6mcoc4NJ2RfTmBP2ve+sMFLrVlbfvo
  00szqeF/TCpSAku+94FUpGPvXdIBFsarYTskpq9pbZbz1Ts3D8OFQyvOaCpPUx3W
  sBb5uoVFmYVYm+gTsLOQqjcgmoi0KoWVI3tM175WrFlN/DA/F6ytSuYJqIYBbG0P
  zI0SqrEVjDhwn1jGs5lr2EUstjH3yPOa8kGNWnTkt/m8rvZjS/bKKBZadyWx0Mxi
  5jjkzsvpyjujr0FPtojsJHGDW1xGDFmXsU0pdwIDAQABAoIBAEdPHigrQOEkkZBW
  rxcfFTR5jFlQp7pLXTyyMlLHIFJZyYldEVFNcA+tKh2ye9t/5M915iq26zIUq9qG
  SO8+0ATqM2dnWGMlzg3Fb74BG1+KNEvHvvhtEYKezpE7yFxbgRDz1EuHcBPmHbDv
  ojOR7MY6s2XKoh3P+uwoQ5e1Y0B9MWSMlJK8b3SR/yTEKb2KyXKOllMmglD1Djv6
  Wi+4nIO78EZuK/auhz6Xx1yCz7H1/q8+qt62HsiYNBK7e6oZ1Sbjf/BfQSINc4Hu
  L3SdKCO4x5T3TLQOUGDMvcvKR1wPdroxJZGsFjMAZAiupP+OJ110mrwnf+gekJQM
  M4jHwSECgYEAzXApsc6qCQmJZbBxFdju+TFSRErRz7wTRqHvJTT5CgxDtN9CTKSJ
  zS+sTJvoK8HE7gBGVYUsyl+iSljpYw+ITpFkq4MvqUXbC1o3zcsfcQ1hpz4NPfdL
  p5Xp+gdofxuH1xFtxCpvB0uknn9sQcb0K4pt7Dr2LWNpxaF2Y6/1sQ0CgYEAwvou
  c6vmOAcyN7BGtKOZOCRSK+P/9ZMkSLzdsgxP5Tr3odCrMfv8uMMV9b+rYJYI5Uyz
  evp322rqnkNSxPf09Dx2UA2BbVk+f/ZzPoG08Xj8Pc3cb4j69Fsv92DkjCQwbgSo
  tdEiJe2m+geOS/JalwcULOuw6+WD9qQrcYl0u5MCgYAm859UMUUYFZDRkRS/+bPF
  184rWKxTYOuettFrEpItj4m+353ofkIKf4GBvQXWVhUKs06ipG+Lp3pT8mu99pH3
  o6Wcx3Df/Xi8vExcXqkFfG4JkcBdAWh8y/XjDEiJ4SRuaMWRLiKDFZqO2sYh6qEd
  KFATPFK05GaHrEeQOyqweQKBgQCp7VrgqvdY60Sj7jihJFfb6yPGZs5kG5oq3pek
  nkBfevXpDDC3vnLyH+waorJc2kXkeeWOj444J8VUqz4Otj/BQJSojiy3vWjQI10r
  I+Yr8ZJ81taASnTU1EhIpCRr0vp2WA8lbqABSE8XZ9Bndk/ngl7eC4fE/+Hz6f6G
  1BJtiwKBgDQsGcH3Qdwv9O/TTLzHNRXroTLP6j4fgZzZlwH8aUXixl1ADXgZtKNk
  7VEzIroUy4ibaius4cvRGkFbpDJHJmu4fIIiJIHQCRcRGaRAvMPTtfPlnA9A8hQR
  SpyS6ZLz9ZXIjKYWl8Qtvrho0OlH/VNuj5/a+7cycnym6/qoBE7M
  -----END RSA PRIVATE KEY-----