HOST: 127.0.0.1
PORT: 8088
DEBUG: false

DEV_MODE: true
SHOW_API_DOC: true

API_V1_STR: "/api/v1"
PROJECT_NAME: "education_ai_chatbot"
AUD_JWT_NAME_FOR_VALIDATION: "education_ai_chatbot"
SWAGGER_URL: './static'

TOKEN_EXP_TIME: 3600

DATABASE_URL: 'postgresql+asyncpg://hanv:thienvu@localhost:5432/chatbot_ai_education'


URL_MAIL: ''

LOG_FILE: "../logs"

LOGGING_LEVEL: 3
ACTION_LOG_ENABLED: True
ACTION_LOG_DEFAULT_ACTOR: root
SYSTEM: "Education AI Chatbot"
WORKERS: 1

ALGORITHM: "RS256"
ACCESS_TOKEN_EXPIRE_DAYS: 1

DEFAULT_COOKIE: "request_state=3b17dda4-96e3-4330-871b-0d9761499f49; access_token_cookie=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6M01ZUXdocllWTkFwckpSS1hqR3ZFcC12c083aG1FZVRFbVJ6aklpTmJFIn0.eyJleHAiOjE2NTg5MDg5NzQsImlhdCI6MTY1ODkwODY3NCwiYXV0aF90aW1lIjoxNjU4OTA3NDAzLCJqdGkiOiIzYWRiYWY0Mi1kZjNlLTQ3ODMtYjdiMC01Y2U3YzBhNjcyN2UiLCJpc3MiOiJodHRwOi8vYXV0aC1vbGQudGkudmlzYy5jb20vYXV0aC9yZWFsbXMvYXV0aG9yaXphdGlvbl93cmFwcGVyIiwiYXVkIjpbImF1dGhvcml6YXRpb25fd3JhcHBlciIsImFjY291bnQiXSwic3ViIjoiNWQ5MzA1YTEtNTQ4MC00NGZiLWFiZTUtN2ZlNzZkMTM0NDFkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXV0aG9yaXphdGlvbl93cmFwcGVyIiwic2Vzc2lvbl9zdGF0ZSI6ImY5MTY0MGNkLWQ3MGUtNGVkMi05YTMzLWZkNTk3MWNiMTk4ZCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1hdXRob3JpemF0aW9uX3dyYXBwZXIiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgYXVkaWVuY2UgZW1haWwgcHJvZmlsZSIsInNpZCI6ImY5MTY0MGNkLWQ3MGUtNGVkMi05YTMzLWZkNTk3MWNiMTk4ZCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoic3VwZXJfdXNlciJ9.kbkaiGS47Mzba1kBjc5PuN5gvaZ7Zg2s-r5zyNfza5KcfCntLm7Urxh08JNxneDAXBHeKnn9NBoyjP0X6crt0WnHL8EyoYTGxBjGBmHCrnPCL_BIgFzt7L6D3nJ3sMBpAWZlJPCvAyMsVSK2uPEyYgFsXaCBrPNw14mIprTHrOnSQuovEr7EADwlhyH9bkE5t0_gqSBJ8obvJpJa6657iGHLonU775JX2EEYUhPeBk60fGnFzgcZVl7Hz4OZfBp0b73-ZvLOliMkSA3xbrHGXxv4M0YclEPNDCdJa6YB8mfMqHxtxRkjlSIuI5J-H1syFugdrrV90bRNhkAPxwUQbA; refresh_token_cookie=Wm1CGt1FN0/1Pmle6IFROFnACf9X4Zzert/gNMgaD76t6RPmmL5k8rbit8aAGx5X22USPlORtyozXkFKjk3ekIB63LhhBelDU/tXLDJ5OhgNHr9U9ReUDJCp06u5bNSgmUTcWEntbVSeIa+2mLR3TeEUOaH8sks36vFK1t6V/1/Da6S+WkLHFJXzSq0OfO4oXyeoTtWv+xmjPmD4OmlrrcS1FbCTwFNFx9fhSGzc0CFuDTLAvM+WWCy7k5Bj6mc0LF078n4t50Qc2ROCyQ1+j5c0JGT+HWgmkC2rzYkLKAh46hc7W3Er/RCUn3qYFRAhD/6REIyga4Oe39g5HRBD4ZtiaZfboIpI1WE/3ejOMKr0xlo4tQqwxMO2EYQH05q7gpTsriH36Q3U2pGsLvbn/RbkG7ViAQGs3YhLLbJx9EJiQjUqBtRXOfBA63MTfuYcqpvyIfZP0IVTYCcYfF7SJdn8jwESWJUSgDuCIs+PJSKU4DixnQoOUdpf4h84bkuJKWUix7+PB+vWpz1Cq5il4cEgm8+bEEjfao4bw6iUWlvVVUCty+D9W//LnSBPjnrVnb3oxz7cUnIzK0895JszR5DkzQZRnDOpTiRLrjqqT4NDWbQ06wcpp+uaGd9yrwgVUOUFDBJkFbU/jkuI9mZYgpdv0jfcBUCT9V3elTg4PIK5fSkBxHAOlywOdcFDA+mOmxzD4NZXYXNyDtbmmtVrf4aRtX4tCfEr9uN15qR1o9QVEckvKROjyXlTTBIYy4l0rf3mLkJUzHDP4RwqWYc"
DEFAULT_ACTOR: "test@gmail.com"